// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA237K-AB6GU9w9sFw1cuwmDEsepjfYSnE',
    appId: '1:748029000235:web:a6ec9a72b13acdd69d086e',
    messagingSenderId: '748029000235',
    projectId: 'ecommerce-5dbfb',
    authDomain: 'ecommerce-5dbfb.firebaseapp.com',
    storageBucket: 'ecommerce-5dbfb.appspot.com',
    measurementId: 'G-EWT0FV89B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWa8vLKPZsrFkYf3b9LDpDDfFHMdkTELo',
    appId: '1:748029000235:android:e14b0996d63010179d086e',
    messagingSenderId: '748029000235',
    projectId: 'ecommerce-5dbfb',
    storageBucket: 'ecommerce-5dbfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnM4-osrtdJs6eOLKa9XRvZ64EY3o6Nxg',
    appId: '1:748029000235:ios:a1e4d06e85e8cb099d086e',
    messagingSenderId: '748029000235',
    projectId: 'ecommerce-5dbfb',
    storageBucket: 'ecommerce-5dbfb.appspot.com',
    iosClientId:
        '748029000235-s730c0qa8kv9muia9gdfphf3s7f8p5cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnM4-osrtdJs6eOLKa9XRvZ64EY3o6Nxg',
    appId: '1:748029000235:ios:a1e4d06e85e8cb099d086e',
    messagingSenderId: '748029000235',
    projectId: 'ecommerce-5dbfb',
    storageBucket: 'ecommerce-5dbfb.appspot.com',
    iosClientId:
        '748029000235-s730c0qa8kv9muia9gdfphf3s7f8p5cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
